services:
  postgres:
    image: postgres:15.3
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - pqdata:/var/lib/postgresql/data

  gateway:
    build: ./gateway
    container_name: gateway
    environment:
      - GIN_MODE=release
      - SERVER_ADDR=0.0.0.0:8080
      - SERVICE_AUTH=auth:8080
      - SERVICE_EVENT=event:8080
    ports:
      - 8080:8080
    depends_on:
      - auth
      - event

  auth:
    build: ./auth-service
    container_name: auth-service
    environment:
      - GIN_MODE=release
      - SERVER_ADDR=0.0.0.0:8080
      - SERVER_CRYPTO=123456
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=postgres
    depends_on:
      - postgres

  event:
    build: ./event-service
    container_name: event-service
    environment:
      - GIN_MODE=release
      - SERVER_ADDR=0.0.0.0:8080
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DBNAME=postgres
    depends_on:
      - postgres

volumes:
  pqdata: